[package]
name = "rust-ice1"
version = "0.1.0"
authors = ["Kevin Darlington <kevin@outroot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
